version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres-devops
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi-crud-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
