apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ahmedk18/fastapi-crud-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_URL
          value: "postgresql+asyncpg://postgres:devpassword@postgres-devops:5432/devops_db"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  ports:
  - port: 8000
  selector:
    app: fastapi
  type: LoadBalancer
